//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionDespachoContable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.creditoFiscal = new HashSet<creditoFiscal>();
        }
    
        public int idCliente { get; set; }
        public string nombreCompleto { get; set; }
        public string nit { get; set; }
        public string registro { get; set; }
        public string giro { get; set; }
        public string direccion { get; set; }
        public int idEstado { get; set; }
        public int idDepartamento { get; set; }
        public int idMunicipio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<creditoFiscal> creditoFiscal { get; set; }
        public virtual departamento departamento { get; set; }
        public virtual estado estado { get; set; }
        public virtual municipio municipio { get; set; }
    }
}
