//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionDespachoContable.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class despachoContableEntities : DbContext
    {
        public despachoContableEntities()
            : base("name=despachoContableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<creditoFiscal> creditoFiscal { get; set; }
        public virtual DbSet<departamento> departamento { get; set; }
        public virtual DbSet<detalleCreditoFiscal> detalleCreditoFiscal { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<municipio> municipio { get; set; }
        public virtual DbSet<servicio> servicio { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<detalleFactura> detalleFactura { get; set; }
        public virtual DbSet<factura> factura { get; set; }
    }
}
