//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionDespachoContable.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class detalleFactura
    {
        public int idDetalle { get; set; }
        public int idFactura { get; set; }

        [Required(ErrorMessage = "Requerido"), Display(Name = "Servicio")]
        public int idServicio { get; set; }

        [Required(ErrorMessage = "Requerido"), Display(Name = "Cantidad")]
        public int cantidad { get; set; }

        [Required(ErrorMessage = "Requerido"), Display(Name = "Precio")]
        public decimal precio { get; set; }

        [Required(ErrorMessage = "Requerido"), Display(Name = "Valor")]
        public decimal valor { get; set; }
    
        public virtual factura factura { get; set; }
        public virtual servicio servicio { get; set; }
    }
}
