//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionDespachoContable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleCreditoFiscal
    {
        public int idDetalle { get; set; }
        public int idCreditoFiscal { get; set; }
        public int idServicio { get; set; }
        public int cantidad { get; set; }
        public decimal precio { get; set; }
        public decimal valor { get; set; }
    
        public virtual creditoFiscal creditoFiscal { get; set; }
        public virtual servicio servicio { get; set; }
    }
}
