//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionDespachoContable.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public factura()
        {
            this.detalleFactura = new HashSet<detalleFactura>();
        }
    
        public int idFactura { get; set; }

        [Required(ErrorMessage = "Requerido"), Display(Name = "Cliente")]
        public int idCliente { get; set; }

        [Required(ErrorMessage = "Requerido"), Display(Name = "IVA")]
        public decimal iva { get; set; }
        [Required(ErrorMessage = "Requerido"), Display(Name = "Total")]
        public decimal total { get; set; }

        [Required(ErrorMessage = "Requerido"), Display(Name = "Fecha")]
        public System.DateTime fecha { get; set; }
        public int numeroDocumento { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleFactura> detalleFactura { get; set; }
    }
}
