//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionDespachoContable.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class usuario
    {
        public int idUsuario { get; set; }

        [Display(Name ="Nombre Completo")]
        [Required(ErrorMessage ="Requerido"),MaxLength(50,ErrorMessage ="Maximo 50")]
        public string nombreCompleto { get; set; }

        [Display(Name = "Usuario")]
        [Required(ErrorMessage = "Requerido"), MaxLength(10, ErrorMessage = "Maximo 10"),MinLength(5,ErrorMessage ="Minimo 5")]
        public string usuario1 { get; set; }

        [Display(Name = "Contraseña")]
        [Required(ErrorMessage = "Requerido"), MaxLength(10, ErrorMessage = "Maximo 10"), MinLength(5, ErrorMessage = "Minimo 5")]
        public string contrasena { get; set; }
    }
}
