//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionDespachoContable.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class usuario
    {
        public int idUsuario { get; set; }

        [Required(ErrorMessage = "Requerido"), Display(Name = "Nombre"), MaxLength(35, ErrorMessage = "Maximo 35")]
        public string nombreCompleto { get; set; }
        
        [Required(ErrorMessage = "Requerido"), Display(Name = "Usuario"), MaxLength(10, ErrorMessage = "Maximo 10")]
        [MinLength(5, ErrorMessage ="Minimo 5")]
        public string usuario1 { get; set; }

        [Required(ErrorMessage = "Requerido"), Display(Name = "Contraseña"), MaxLength(10, ErrorMessage = "Maximo 10")]
        [MinLength(5, ErrorMessage = "Minimo 5")]
        public string contrasena { get; set; }
    }
}
